:root{--bg:#07111f;--bg-soft:#0b1728;--panel:rgba(15,29,48,.72);--line:rgba(151,178,205,.14);--text:#f4f8fc;--muted:#a9b8c9;--accent:#34d5ff;--accent-2:#7b61ff;--shadow:0 24px 70px rgba(0,0,0,.28);--radius:24px;--max:1180px}
*{margin:0;padding:0;box-sizing:border-box}
html{scroll-behavior:smooth}
body{font-family:'DM Sans',sans-serif;background:var(--bg);color:var(--text);line-height:1.7;overflow-x:hidden}
body:before{content:"";position:fixed;inset:0;pointer-events:none;background:radial-gradient(circle at 80% 10%,rgba(52,213,255,.07),transparent 28%),radial-gradient(circle at 15% 45%,rgba(123,97,255,.05),transparent 25%);z-index:-2}
a{color:inherit;text-decoration:none}.container{width:min(calc(100% - 48px),var(--max));margin:auto}.section{padding:120px 0;position:relative}.section-alt{background:rgba(255,255,255,.018);border-top:1px solid rgba(255,255,255,.025);border-bottom:1px solid rgba(255,255,255,.025)}
.scroll-progress{position:fixed;top:0;left:0;width:0;height:3px;background:linear-gradient(90deg,var(--accent),var(--accent-2));z-index:2000}
.site-header{position:fixed;top:0;left:0;width:100%;z-index:1000;background:rgba(7,17,31,.65);backdrop-filter:blur(18px);border-bottom:1px solid transparent;transition:.3s}.site-header.scrolled{border-color:var(--line);background:rgba(7,17,31,.88)}
.navbar{height:78px;display:flex;align-items:center;justify-content:space-between}.brand{font-family:'Space Grotesk',sans-serif;font-size:26px;font-weight:700;letter-spacing:-1px}.brand span{color:var(--accent)}
.nav-links{display:flex;align-items:center;gap:30px;list-style:none}.nav-link{font-size:14px;color:#b9c5d3;transition:.25s;position:relative}.nav-link:after{content:"";position:absolute;left:0;bottom:-8px;width:0;height:2px;background:var(--accent);transition:.25s}.nav-link:hover,.nav-link.active{color:#fff}.nav-link.active:after{width:100%}.menu-toggle{display:none;background:none;border:0;cursor:pointer}.menu-toggle span{display:block;width:25px;height:2px;background:#fff;margin:5px;border-radius:5px}
.hero{min-height:100vh;padding-top:150px;display:flex;align-items:center;overflow:hidden}.hero-grid{display:grid;grid-template-columns:1.05fr .95fr;gap:80px;align-items:center}.eyebrow{font-size:12px;text-transform:uppercase;letter-spacing:2px;color:var(--accent);font-weight:700;display:flex;align-items:center;gap:10px;margin-bottom:22px}.eyebrow span{width:28px;height:1px;background:var(--accent);display:inline-block}.hero h1,.section-heading h2,.contact-card h2{font-family:'Space Grotesk',sans-serif;letter-spacing:-2.5px;line-height:1.06}.hero h1{font-size:clamp(48px,6vw,78px);max-width:760px}.hero h1 em,.section-heading h2 em,.contact-card h2 em{font-style:normal;color:var(--accent)}.hero-text{max-width:680px;color:var(--muted);font-size:18px;margin:28px 0 34px}.hero-actions{display:flex;gap:14px;flex-wrap:wrap}.btn{display:inline-flex;align-items:center;justify-content:center;gap:10px;padding:13px 21px;border-radius:12px;font-size:14px;font-weight:700;transition:.3s;border:1px solid transparent}.btn-primary{background:var(--accent);color:#03121c}.btn-primary:hover{transform:translateY(-3px);box-shadow:0 14px 35px rgba(52,213,255,.2)}.btn-ghost{border-color:var(--line);background:rgba(255,255,255,.025);color:#e8eef5}.btn-ghost:hover{border-color:rgba(52,213,255,.45);transform:translateY(-3px)}.social-row{display:flex;gap:14px;align-items:center;margin-top:30px;color:#7f91a5;font-size:13px}.social-row span{width:4px;height:4px;border-radius:50%;background:#415269}.social-row a:hover{color:var(--accent)}
.hero-visual{height:540px;display:flex;align-items:center;justify-content:center;position:relative}.profile-frame{width:min(400px,75vw);height:min(400px,75vw);border-radius:50%;padding:8px;background:linear-gradient(135deg,var(--accent),var(--accent-2));position:relative;box-shadow:0 0 90px rgba(52,213,255,.15)}.profile-frame:before{content:"";position:absolute;inset:18px;border:1px solid rgba(255,255,255,.22);border-radius:50%;z-index:1}.profile-frame img{width:100%;height:100%;border-radius:50%;object-fit:cover;background:var(--bg-soft);position:relative;z-index:2}.profile-glow{position:absolute;inset:-35px;border-radius:50%;background:radial-gradient(circle,rgba(52,213,255,.12),transparent 62%);filter:blur(5px)}.orbit{position:absolute;border:1px solid rgba(52,213,255,.14);border-radius:50%}.orbit-one{width:510px;height:510px}.orbit-two{width:610px;height:610px;border-color:rgba(123,97,255,.09)}.floating-card{position:absolute;padding:14px 17px;background:rgba(12,27,45,.82);backdrop-filter:blur(14px);border:1px solid var(--line);border-radius:15px;box-shadow:var(--shadow);z-index:4}.floating-card strong{display:block;font-size:13px}.floating-card small{color:#8496aa;font-size:11px}.card-top{top:65px;right:10px}.card-bottom{bottom:65px;left:0}
.stats-strip{border-top:1px solid var(--line);border-bottom:1px solid var(--line);background:rgba(255,255,255,.015)}.stats-grid{display:grid;grid-template-columns:repeat(4,1fr)}.stat{padding:28px 20px;text-align:center;border-right:1px solid var(--line)}.stat:last-child{border-right:0}.stat strong{font-family:'Space Grotesk';font-size:34px}.stat strong span{color:var(--accent)}.stat p{font-size:12px;color:#7f91a5;text-transform:uppercase;letter-spacing:1.2px}
.split-section{display:grid;grid-template-columns:.9fr 1.1fr;gap:100px}.section-heading h2{font-size:clamp(38px,4.4vw,58px)}.section-heading>p:last-child,.about-content p,.research-feature>p:not(.research-kicker){color:var(--muted)}.about-content{padding-top:12px}.about-content p{font-size:17px;margin-bottom:20px}.about-tags,.mini-tags,.skill-list,.project-tags{display:flex;flex-wrap:wrap;gap:8px}.about-tags{margin-top:28px}.about-tags span,.mini-tags span,.skill-list span,.project-tags span,.research-interests span{border:1px solid var(--line);background:rgba(255,255,255,.025);color:#aebdcd;padding:6px 10px;border-radius:8px;font-size:11px}
.centered{text-align:center;max-width:700px;margin:0 auto 55px}.centered .eyebrow{justify-content:center}
.timeline{max-width:850px;margin:auto;border-left:1px solid rgba(52,213,255,.22);padding-left:40px}.timeline-item{position:relative}.timeline-dot{position:absolute;left:-47px;top:32px;width:13px;height:13px;background:var(--accent);border-radius:50%;box-shadow:0 0 0 7px rgba(52,213,255,.08)}.timeline-card{padding:32px;border:1px solid var(--line);background:var(--panel);border-radius:var(--radius);box-shadow:var(--shadow)}.timeline-label,.card-label,.research-kicker{font-size:11px;text-transform:uppercase;letter-spacing:1.5px;color:var(--accent);font-weight:700}.timeline-card h3{font-family:'Space Grotesk';font-size:26px;margin:8px 0 12px}.timeline-card p:not(.timeline-label){color:var(--muted)}.mini-tags{margin-top:20px}
.skills-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:16px}.skill-card{padding:28px;border:1px solid var(--line);background:var(--panel);border-radius:20px;transition:.3s}.skill-card:hover,.project-card:hover,.achievement-card:hover{transform:translateY(-6px);border-color:rgba(52,213,255,.25)}.skill-number{color:#52677e;font-family:'Space Grotesk';font-size:12px}.skill-card h3{font-family:'Space Grotesk';font-size:21px;margin:26px 0 10px}.skill-card p{color:var(--muted);font-size:14px;margin-bottom:22px}.skill-list span{font-size:10px}
.projects-grid{display:grid;grid-template-columns:1.2fr .8fr;gap:18px}.project-card{min-height:390px;padding:28px;border:1px solid var(--line);background:var(--panel);border-radius:var(--radius);display:flex;flex-direction:column;transition:.3s}.project-card.featured{background:linear-gradient(145deg,rgba(52,213,255,.08),rgba(123,97,255,.04) 50%,var(--panel))}.project-top,.project-footer{display:flex;justify-content:space-between;align-items:center}.project-index{font-family:'Space Grotesk';font-size:13px;color:var(--accent)}.project-type{font-size:10px;text-transform:uppercase;letter-spacing:1px;color:#73879c}.project-body{margin:auto 0}.project-body h3{font-family:'Space Grotesk';font-size:34px;margin-bottom:12px}.project-body p{color:var(--muted);max-width:650px}.project-tags{margin-top:22px}.project-tags span{color:#c6d2de}.project-footer{padding-top:22px;margin-top:25px;border-top:1px solid var(--line);font-size:11px;color:#74879c}.arrow{font-size:20px;color:var(--accent)}.section-note{text-align:center;color:#687b90;font-size:12px;margin-top:22px}
.research-layout{display:grid;grid-template-columns:.85fr 1.15fr;gap:80px;align-items:center}.research-panel{border:1px solid var(--line);background:var(--panel);border-radius:var(--radius);overflow:hidden}.research-feature{padding:38px}.research-feature h3{font-family:'Space Grotesk';font-size:30px;line-height:1.2;margin:12px 0 15px}.research-status{display:inline-block;margin-top:22px;padding:7px 11px;border-radius:8px;background:rgba(52,213,255,.08);color:var(--accent);font-size:10px;text-transform:uppercase;letter-spacing:1px}.research-interests{display:flex;flex-wrap:wrap;gap:8px;padding:24px 38px;border-top:1px solid var(--line)}.research-interests span{font-size:11px}
.achievement-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:16px}.achievement-card{display:flex;gap:18px;padding:25px;border:1px solid var(--line);background:var(--panel);border-radius:18px;transition:.3s}.achievement-icon{font-size:22px;color:var(--accent);width:28px}.achievement-card h3{font-family:'Space Grotesk';font-size:20px;margin:5px 0}.achievement-card p:last-child{color:var(--muted);font-size:13px}
.contact-section{padding-top:80px}.contact-card{display:grid;grid-template-columns:1.2fr .8fr;gap:60px;padding:60px;border:1px solid rgba(52,213,255,.18);border-radius:30px;background:radial-gradient(circle at 85% 20%,rgba(52,213,255,.09),transparent 30%),var(--panel);box-shadow:var(--shadow)}.contact-card h2{font-size:clamp(40px,5vw,62px)}.contact-card>div:first-child>p:last-child{color:var(--muted);max-width:650px;margin-top:22px}.contact-actions{display:flex;flex-direction:column;align-items:flex-start;justify-content:center;gap:12px}.contact-actions small{color:#687b90;font-size:10px}.contact-actions strong{color:#9eb0c3}
.footer{padding:55px 0;border-top:1px solid var(--line);background:#050c17}.footer-inner{display:grid;grid-template-columns:1fr auto 1fr;align-items:end;gap:30px}.footer p{color:#6f8194;font-size:12px;margin-top:7px}.footer-links{display:flex;gap:22px;font-size:12px;color:#8c9caf}.footer-links a:hover{color:var(--accent)}.copyright{text-align:right}
.reveal{opacity:0;transform:translateY(22px);transition:opacity .7s ease,transform .7s ease}.reveal.visible{opacity:1;transform:none}.reveal-delay{transition-delay:.12s}
@media(max-width:1000px){.nav-links{gap:18px}.hero-grid,.split-section,.research-layout{grid-template-columns:1fr;gap:55px}.hero{text-align:center}.hero .eyebrow,.social-row{justify-content:center}.hero-text{margin-left:auto;margin-right:auto}.hero-actions{justify-content:center}.hero-visual{height:500px}.skills-grid{grid-template-columns:repeat(2,1fr)}.projects-grid{grid-template-columns:1fr}.contact-card{grid-template-columns:1fr}.footer-inner{grid-template-columns:1fr;text-align:center}.copyright{text-align:center}.footer-links{justify-content:center}}
@media(max-width:760px){.container{width:min(calc(100% - 32px),var(--max))}.section{padding:85px 0}.navbar{height:70px}.menu-toggle{display:block}.nav-links{position:absolute;top:70px;left:16px;right:16px;display:none;flex-direction:column;align-items:stretch;gap:0;padding:10px;background:rgba(8,20,34,.97);border:1px solid var(--line);border-radius:16px;box-shadow:var(--shadow)}.nav-links.open{display:flex}.nav-link{padding:12px 14px}.nav-link:after{display:none}.hero{padding-top:120px}.hero h1{font-size:45px}.hero-text{font-size:16px}.hero-visual{height:430px}.profile-frame{width:300px;height:300px}.orbit-one{width:360px;height:360px}.orbit-two{width:430px;height:430px}.floating-card{display:none}.stats-grid{grid-template-columns:repeat(2,1fr)}.stat{border-bottom:1px solid var(--line)}.stat:nth-child(2){border-right:0}.stat:nth-child(3),.stat:nth-child(4){border-bottom:0}.split-section{gap:30px}.skills-grid,.achievement-grid{grid-template-columns:1fr}.research-layout{gap:35px}.contact-card{padding:35px 24px}.footer-links{flex-wrap:wrap}.project-card{min-height:350px}}
